### DISCUSSION TITLE
The problem with the url() function when using data URL

### DISCUSSION THREAD

**Discussion by addison74** [OpenMage/magento-lts#3907] [Questions & Answers]
I have to revamp a whole OpenMage theme based on Bootstrap 5.3 (I tried Tailwind+DaisyUI before but I don't have too much time for learning new stuff). I discovered this issue when I tried implementing a modal. The close X sign was not appearing in the modal box, then I inspected the CSS code.

This is the **Bootstrap CSS file** content for the **.btn-close** class:

```scss
.btn-close {
  box-sizing: content-box;
  width: 1em;
  height: 1em;
  padding: 0.25em 0.25em;
  color: #000;
  background: transparent url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23000'%3e%3cpath d='M.293.293a1 1 0 0 1 1.414 0L8 6.586 14.293.293a1 1 0 1 1 1.414 1.414L9.414 8l6.293 6.293a1 1 0 0 1-1.414 1.414L8 9.414l-6.293 6.293a1 1 0 0 1-1.414-1.414L6.586 8 .293 1.707a1 1 0 0 1 0-1.414z'/%3e%3c/svg%3e") center/1em auto no-repeat;
  border: 0;
  border-radius: 0.375rem;
  opacity: 0.5;
}
```

This is the **CSS file from the browser cache** for the same class:

```scss
.btn-close {
  box-sizing: content-box;
  width: 1em;
  height: 1em;
  padding: 0.25em 0.25em;
  color: #000;
  background: transparent url("https://www.mydomain.tld/skin/frontend/default/custom_theme/css/data:image/svg+xml,%3csv")xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23000'%3e%3cpath d='M.293.293a1 1 0 0 1 1.414 0L8 6.586 14.293.293a1 1 0 1 1 1.414 1.414L9.414 8l6.293 6.293a1 1 0 0 1-1.414 1.414L8 9.414l-6.293 6.293a1 1 0 0 1-1.414-1.414L6.586 8 .293 1.707a1 1 0 0 1 0-1.414z'/%3e%3c/svg%3e") center/1em auto no-repeat;
  border: 0;
  border-radius: 0.375rem;
  opacity: 0.5;
}
```

As can be seen, the path where the bootstrap.css file is located was taken in the url() function even it is a data URL. Did anyone encountered this issue and how could I avoid it and stop adding the absolute path? There are too many Bootstrap classes that have this issue.
