### ISSUE TITLE
Admin theme: missing CSS for active links/sections 

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#4207]
Hey @aterjung,

active sections should have a slightly different backround color.

Something like ...

```css
    &.level1, &.level2, &.level3 {
      > a {
        &.active {
          background: red;
        }
      }
    }
```

You know your color shemes, can you please provide a fix?
